version: "3"

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "1234:1234"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=dev
      - POSTGRES_DB=dev

volumes:
  postgres: